### ISSUE TITLE
Loading picture covers 'Attach Debugger' Dialog

### ISSUE THREAD

**Issue by 3ti65** [kiwidoggie/Rime#10]
If you start Rime with -debug it will open 2 windows, the loading picture with the long neck guy and the 'Attach Debugger' Dialog. The latter is not reachable because the loading picture covers it completely. Not even Alt-Tabbing or anything will do. Only workaround as of now is to manually kill the picture window in the taskmanager. Pls fix

Edit: Also, 'Attach Debugger' Dialog doesnt show up as Icon in the taskbar. Would be a bit more obvious.

**Comment by kiwidoggie** [comment]
This should be fixed in build 1.6.6176.30490.

**Comment by 3ti65** [comment]
works! :+1:
