### ISSUE TITLE
Issue where all files don't get copied from update directory.

### ISSUE THREAD

**Issue by kiwidoggie** [kiwidoggie/Rime#15]
Powback - Today at 4:56 PM
Regarding the updater, it doesn't automatically move fbcc to the root folder after update
So it doesn't detect that it's fully updated

**Comment by Powback** [comment]
Happens when the file doesn't already exist in the root directory.

**Comment by kiwidoggie** [comment]
This has been fixed in 1.6.6220.21064 which has been deployed to development branch.
