### ISSUE TITLE
Documentation chm does not exist anymore.

### ISSUE THREAD

**Issue by Powback** [kiwidoggie/Rime#20]
The documentation accessed by pressing F1 does not exist anymore, making both the shortcut and the menu option useless.

**Comment by kiwidoggie** [comment]
This is slated for removal, I forgot to remove the option, or redirect them to the new page which will be located on the Modders Link wiki at  https://modders.link/wiki

**Comment by kiwidoggie** [comment]
This has been fixed in 1.6.6310.20441
