### ISSUE TITLE
Add startup parameter ' -mod "string" ' to directly load a mod on startup

### ISSUE THREAD

**Issue by 3ti65** [kiwidoggie/Rime#30]
Same as project parameter. But this one should also load the correct project before loading the mod.

**Comment by 3ti65** [comment]
To keep it simple we can also define the -project param to be set as a requirement for this one.

**Comment by kiwidoggie** [comment]
This has been completed in build 1.6.6518.34160 (not pushed yet) with an untested state, if there is an issue with it re-open the issue.
