### ISSUE TITLE
Improper handling of elements within lists

### ISSUE THREAD

**Issue by Powback** [kiwidoggie/Rime#5]
Lua should not be generated on list items. This makes us unable to open items.
Perhaps Rime only checks the root type instead of the parent type of the selected item?

This is the result of clicking on one of the children in the list. Clicking on the textbox will make you edit the text instead of opening the partition.
![image](http://i.imgur.com/f2DvV7s.png)

**Comment by kiwidoggie** [comment]
This is due to the PartitionBrowser not handling sub-classes as fully different objects. This should be corrected in the new UI that is coming.

**Comment by kiwidoggie** [comment]
NoFaTe has fixed this in a previous build.
