### ISSUE TITLE
Investigate Auto-Updater failing issues

### ISSUE THREAD

**Issue by kiwidoggie** [kiwidoggie/Rime#52]
"It works on my PC" is not enough for one of the most critical parts of Rime. If the updates fail for you in any way, write what OS you are running, the permissions on the folder (Right Click->Properties->Security->Users) and what error message if any failed for you.

**Comment by 3ti65** [comment]
Is it still bugged?

**Comment by kiwidoggie** [comment]
@3ti65 I could never reproduce the issues that you were having, but I believe I fixed them. After I deploy the new update, I will have all the current testers try.

**Comment by kiwidoggie** [comment]
Related to #27

**Comment by Powback** [comment]
You should upload a new clean version to ensure that there are no old or conflicting old dlls.
