### ISSUE TITLE
Move and rename "Plugins" toolbar.

### ISSUE THREAD

**Issue by Powback** [kiwidoggie/Rime#59]
The "Plugins" toolbar should be renamed to "Tools" or "Windows", and should only display plugins containing an UI. 

A list of loaded plugins should instead be moved to a new window in either "properties", "about" or in a new "plugins" option in the file about menu. Once a plugin is clicked, it should show the description and creators of said plugin.

**Reasoning:**
"Internal" plugins (Plugins without an UI) should not be visible directly to the user if they don't provide the user with instant results. Having plugins that "do nothing" will make the software feel unresponsive. 

For example, GameContext is launched at boot and provides the user with a "Levels" menu. Therefore it serves no purpose to have it listed in the plugins menu. 

I suggest that we create a wireframe template of how the plugin system should look and function ideally.

**Comment by 3ti65** [comment]
Moved to gitlab issue tracker
