### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by 3ti65** [kiwidoggie/Rime#9]
Debug mode changed and now the flag in the old .exe.config will crash Rime. The new .exe.config doesnt feature the debugmode flag anymore, but it also removes the only known ability (to me at least) to actually get into debugmode and attach a debugger.

thx<3

**Comment by kiwidoggie** [comment]
Added functionality in build 1.4.6076.35415. Will get pushed out on next update.

**Comment by 3ti65** [comment]
god loves you
